var app = angular.module('main', []) 
	.controller('main_controller', main_controller) 
	.service("accessDataService", accessDataService) 
	.service('session', sessionService)
	.service('auth', AuthService)